### ISSUE TITLE
white spaces in the class attribute of "offline-ui-waiting" div

### ISSUE THREAD

**Issue by blackblood** [craigshoemaker/offlinejs-simulate-ui#2]
When I check the checkbox to simulate the app being offline, I see increasing white spaces between the class attributes "offline-ui-down" and "offline-ui-waiting". I've tested this scenario on google chrome

**Comment by craigshoemaker** [comment]
What do you mean by increasing white spaces?

**Comment by blackblood** [comment]
I mean 

```
<div class='offline-ui-down offline-ui-waiting'>
```

after sometime becomes

```
<div class='offline-ui-down                       offline-ui-waiting'>
```

and the space keeps increasing

**Comment by craigshoemaker** [comment]
gotcha - that's actually the functionality of Offline.js. [You'll want to open an issue over there](https://github.com/hubspot/offline/issues?page=1&state=open).
