### ISSUE TITLE
Save offline status while navigate between pages

### ISSUE THREAD

**Issue by leocaseiro** [craigshoemaker/offlinejs-simulate-ui#4]
I really liked this library, but I was wondering if we could add some kind off cache, with localstorage for example, and than, would be saved while refresh or change pages.
That would be easier to debug some offline warning behaviours.

**Comment by leocaseiro** [comment]
ping

**Comment by craigshoemaker** [comment]
Not sure when I can get to this, but PRs are always welcome :smile:

**Comment by leocaseiro** [comment]
Will work on something...

**Comment by craigshoemaker** [comment]
Closing this for now. Will look for possible PR in future.

**Comment by leocaseiro** [comment]
no worries
