### ISSUE TITLE
Problem with angularjs

### ISSUE THREAD

**Issue by fabdelgado** [craigshoemaker/offlinejs-simulate-ui#5]
I'm using with AngularJS.
When the connection returns to obtain error console
`Uncaught TypeError: Cannot read property 'statusText' of null`

**Comment by fabdelgado** [comment]
Detail:
`angular.js:11389 Uncaught TypeError: Cannot read property 'statusText' of nullrequestLoaded @ angular.js:11389a.onprogress.a.onload @ offline.min.js:2`

**Comment by craigshoemaker** [comment]
Not sure what the issue might be here. I have used with Angular without any problem. How are you setting it up in your application?

**Comment by craigshoemaker** [comment]
Closing this issue as this thread hasn't been updated in a while. Please add a new issue or re-open if you need more help.
