### ISSUE TITLE
Hiding elements when offline/online

### ISSUE THREAD

**Issue by TravisHiscock** [craigshoemaker/offlinejs-simulate-ui#6]
Not sure this is the right place to ask, but here goes.

I am using offline.js and the notifications etc are working fine, but I would like to hide some page elements when offline is triggered.  I see this demo page of yours hides/displays the logon panel, even when not triggered by youer checkbox, but I cant for the life of me work out how the display:block and display:none styles are being applied.

Can you give me some pointers?

Regards, Travis

**Comment by craigshoemaker** [comment]
@TravisHiscock take a look at the [sample source](https://github.com/craigshoemaker/offlinejs-simulate-ui/blob/master/index.html#L99). The page listens for Offline.js events and then responds accordingly.
